# Generated by Django 3.1.1 on 2020-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minister_name', models.CharField(max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('party', models.CharField(max_length=64, null=True)),
                ('date_of_birth', models.CharField(max_length=10, null=True)),
                ('place_of_birth', models.CharField(max_length=64, null=True)),
                ('languages', models.CharField(max_length=64, null=True)),
                ('proffesion', models.CharField(max_length=128)),
            ],
        ),
    ]
